// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoOptica.BD.Data;

#nullable disable

namespace ProyectoOptica.BD.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20251001084316_Renombrar_Turno_FechaHoraUtc_a_FechaHora")]
    partial class Renombrar_Turno_FechaHoraUtc_a_FechaHora
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProyectoOptica.BD.Data.Entity.Reserva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreadaUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailCliente")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NombreCliente")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Notas")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TurnoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "TurnoId" }, "UQ_Reserva_Turno")
                        .IsUnique();

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("ProyectoOptica.BD.Data.Entity.Turno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Creada")
                        .HasColumnType("datetime2");

                    b.Property<int>("DuracionMinutos")
                        .HasColumnType("int");

                    b.Property<bool>("EstaReservado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "EstaReservado", "FechaHora" }, "Turno_Disponibles_IX");

                    b.ToTable("Turnos");
                });

            modelBuilder.Entity("ProyectoOptica.BD.Data.Entity.Reserva", b =>
                {
                    b.HasOne("ProyectoOptica.BD.Data.Entity.Turno", "Turno")
                        .WithOne("Reserva")
                        .HasForeignKey("ProyectoOptica.BD.Data.Entity.Reserva", "TurnoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Reservas_Turnos_TurnoId");

                    b.Navigation("Turno");
                });

            modelBuilder.Entity("ProyectoOptica.BD.Data.Entity.Turno", b =>
                {
                    b.Navigation("Reserva");
                });
#pragma warning restore 612, 618
        }
    }
}
