// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoOptica.BD.Data;

#nullable disable

namespace ProyectoOptica.BD.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20251001053837_Inicio")]
    partial class Inicio
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProyectoOptica.BD.Data.Entity.Turno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DuracionMinutos")
                        .HasColumnType("int");

                    b.Property<bool>("EstaReservado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaHoraUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "EstaReservado", "FechaHoraUtc" }, "Turno_Disponibles_IX");

                    b.HasIndex(new[] { "FechaHoraUtc" }, "Turno_UQ_FechaHora")
                        .IsUnique();

                    b.ToTable("Turnos");
                });
#pragma warning restore 612, 618
        }
    }
}
